### ISSUE TITLE
Can't get WGDashboard to run behind traefik proxy

### ISSUE THREAD

**Issue by lakemike** [donaldzou/WGDashboard#186]
**Describe The Problem**
I can't get WGDashboard to run behind the traefik proxy. Have tried the configuration below. Is there any extra flag required to get this to work? Maybe due to the early stage of the project that this isn't working yet? Could be a feature request not a bug. I should add that directly accessing WGDashboard via the http URL works fine.

** traefik configuration **
```
http:
  routers:
    route-wgdashboard:
      rule: "Host(`wgdashboard.mydomain.tld`)"
      tls:
        certResolver: default
      service: wgdashboard-service
      entryPoints:
        - https

  services:
    wgdashboard-service:
      loadBalancer:
        servers:
          - url: "http://159.159.159.159:10086"
        passHostHeader: true
```
