### ISSUE TITLE
Docker served on an unreliable site

### ISSUE THREAD

**Issue by hoggatt** [donaldzou/WGDashboard#326]
For @DaanSelen 

The site hosting docker is down:

![image](https://github.com/user-attachments/assets/98107cb4-13cc-4506-b885-7fb2d74fc1c6)

I get this error when pulling docker:
![image](https://github.com/user-attachments/assets/4599c6b8-53e3-4323-a2a5-8381b43f116b)

I'd strongly recommend hosting the docker repo on github since it is a more reliable service.

**Comment by hoggatt** [comment]
I found your commit proposing a new docker container. Here are the errors I get now:

 ```
Starting the WireGuard Dashboard Docker container.
---------------------    CLEAN UP    -----------------------
Looking for remains of previous instances...
No pid remains found, continuing.
No pycaches found, continuing.
Setting permissions to not be world-accesible.
chmod: cannot access '/etc/wireguard/*': No such file or directory
---------------------  STARTING CORE -----------------------
Standard WG0 Configuration file not found, grabbing template.
Activating Python venv and executing the WireGuard Dashboard service.
/entrypoint.sh: line 47: /opt/wireguarddashboard/src/venv/bin/activate: No such file or directory
/entrypoint.sh: line 48: cd: /opt/wireguarddashboard/src: No such file or directory
------------------------------------------------------------
Setting relevant variables for operation.
Changing timezone.
grep: /opt/wireguarddashboard/src/wg-dashboard.ini: No such file or directory
Changing default dns.
sed: can't read /opt/wireguarddashboard/src/wg-dashboard.ini: No such file or directory
Trying to fetch the Public-IP using ifconfig.me: [redacted]
sed: can't read /opt/wireguarddashboard/src/wg-dashboard.ini: No such file or directory
------------------------------------------------------------
Ensuring container continuation.
find: '/opt/wireguarddashboard/src/log': No such file or directory
```

**Comment by hoggatt** [comment]
Are you trying to wireguard from inside the container? I'd prefer to run it on my host for maximum stability and just run the web interface VIA docker. Is this possible?

**Comment by DaanSelen** [comment]
> For @DaanSelen
> 
> The site hosting docker is down:
> 
> ![image](https://private-user-images.githubusercontent.com/37279082/360309309-98107cb4-13cc-4506-b885-7fb2d74fc1c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDkyMjQsIm5iZiI6MTcyNDMwODkyNCwicGF0aCI6Ii8zNzI3OTA4Mi8zNjAzMDkzMDktOTgxMDdjYjQtMTNjYy00NTA2LWI4ODUtN2ZiMmQ3NGZjMWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA2NDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYzZhZmNjMGJjOGZjYmRjNDM0NmY0MjdlZTVkNzNkMTY3OTcwMmQyYzkxNDhjNjY2NzIxNDM2Y2I3OWQ4NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u-SpmM6A_P17bx6xZnxp8-T86ig2XBPbadKVhk3a9EQ)
> 
> I get this error when pulling docker: ![image](https://private-user-images.githubusercontent.com/37279082/360309632-4599c6b8-53e3-4323-a2a5-8381b43f116b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDkyMjQsIm5iZiI6MTcyNDMwODkyNCwicGF0aCI6Ii8zNzI3OTA4Mi8zNjAzMDk2MzItNDU5OWM2YjgtNTNlMy00MzIzLWEyYTUtODM4MWI0M2YxMTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA2NDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMmFmM2FjYTlmMjQ1YjliOTBkN2FhMjZkYmE2ZDA4NGI1NzI4N2VkNGYyNDk3OTI1NzU4ZTE5ZTliNDU1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._gNpa2rDlkeHxhHYM--ZCwPs15YbgdnLa2UKxF6iY_c)
> 
> I'd strongly recommend hosting the docker repo on github since it is a more reliable service.

Hello @hoggatt, thanks for notificing I was just yesterday busy with moving my efforts to Docker Hub, instead of my homelab, which is repo.nerthus.nl. I will keep you updated.

For the errors, please provide some context.

**Comment by hoggatt** [comment]
Hopefully my other comments add some context. Biggest question I have: is the docker container meant to be just the wireguard dashboard, or is it meant to run wireguard itself + the dashboard? It's just not 100% clear which is the goal.

**Comment by DaanSelen** [comment]
> Hopefully my other comments add some context. Biggest question I have: is the docker container meant to be just the wireguard dashboard, or is it meant to run wireguard itself + the dashboard? It's just not 100% clear which is the goal.

The container has the wireguard and wireguard-tools package installed, with WGDashboard on op.
So yes, its a VPN + Dashboard.

**Comment by DaanSelen** [comment]
Hi @hoggatt, you were right. My server hang itself and it now back but this ideally should not be the option, pulling its latest image from my server and pushing it to Docker Hub under a specific label, I keep you updated.

**Comment by DaanSelen** [comment]
I've reread your question and if you already have wireguard installed on your system, you can pass the configurations from the host to the container. In the volumes, remove the conf entry and replace it with `/etc/wireguard:/etc/wireguard` this maps the host directory on the host to the container.

**Comment by DaanSelen** [comment]
@hoggatt please check the new image I am working on called `dselen/wgdashboard:dev`

I am using this compose to deploy it:
```
services:
  wireguard-dashboard:
    image: dselen/wgdashboard:dev
    restart: unless-stopped
    container_name: wire-dash
    environment:
      #- tz=                # <--- Set container timezone, default: Europe/Amsterdam.
      #- global_dns=        # <--- Set global DNS address, default: 1.1.1.1.
      - enable=wg0      # <--- Set the interfaces that will be enabled on startup, default: none. The option "off" is also allowed.
      - isolate=wg0     # <--- When set to true, it disallows peers to talk to eachother, setting to false, allows it, default: true.
      #- public_ip=         # <--- Set public IP to ensure the correct one is chosen, defaulting to the IP give by ifconfig.me.
    ports:
      - 10086:10086/tcp
      - 51820:51820/udp
    volumes:
      - conf:/etc/wireguard
      - app:/opt/wireguarddashboard
    cap_add:
      - NET_ADMIN

volumes:
  conf:
  app:
```
Adjust the volumes as needed, but to disable the usage of WireGuard itself, I need to look into that.

**Comment by hoggatt** [comment]
Thanks for the update. Here's my config:

```
services:
  wireguard-dashboard:
    image: dselen/wgdashboard:dev
    restart: unless-stopped
    container_name: WGDashboard
    environment:
      - tz=America/Chicago
      #- global_dns=
      - enable=wg0
      # - isolate=wg0
      #- public_ip=
    ports:
      - 10087:10086/tcp
      - 51821:51820/udp
    volumes:
      - /etc/wireguard:/etc/wireguard
      - /data/wgdashboard/app:/opt/wireguarddashboard
    cap_add:
      - NET_ADMIN
```

And here is the log. Seems to be having issues with `/opt/wireguarddashboard`:

```
WGDashboard  | Starting the WireGuard Dashboard Docker container.
WGDashboard  | ------------------------ CLEAN UP --------------------------
WGDashboard  | Looking for remains of previous instances...
WGDashboard  | No pid remains found, continuing.
WGDashboard  | No pycaches found, continuing.
WGDashboard  | Activating Python venv and executing the WireGuard Dashboard service.
WGDashboard  | ---------------------- STARTING CORE -----------------------
WGDashboard  | Standard WG0 Configuration file found, using that.
WGDashboard  | Activating Python venv and executing the WireGuard Dashboard service.
WGDashboard  | ------------- SETTING ENVIRONMENT VARIABLES ----------------
WGDashboard  | /entrypoint.sh: line 36: /opt/wireguarddashboard/src/venv/bin/activate: No such file or directory
WGDashboard  | /entrypoint.sh: line 37: cd: /opt/wireguarddashboard/src: No such file or directory
WGDashboard  | /entrypoint.sh: line 57: /opt/wireguarddashboard/src/venv/bin/activate: No such file or directory
WGDashboard  | /entrypoint.sh: line 58: cd: /opt/wireguarddashboard/src: No such file or directory
WGDashboard  | Changing timezone.
WGDashboard  | grep: /opt/wireguarddashboard/src/wg-dashboard.ini: No such file or directory
WGDashboard  | Changing default dns.
WGDashboard  | sed: can't read /opt/wireguarddashboard/src/wg-dashboard.ini: No such file or directory
WGDashboard  | Trying to fetch the Public-IP using ifconfig.me: [redacted]
WGDashboard  | sed: can't read /opt/wireguarddashboard/src/wg-dashboard.ini: No such file or directory
WGDashboard  | -------------- ENSURING CONTAINER CONTINUATION -------------
WGDashboard  | Ensuring container continuation.
WGDashboard  | find: '/opt/wireguarddashboard/src/log': No such file or directory
```

The shared folder I'm using on my system does exist, but is empty.
