### ISSUE TITLE
Support AmneziaWG

### ISSUE THREAD

**Issue by RNDpacman** [donaldzou/WGDashboard#370]
Is there any support planned for the obfuscated version of wireguard from amnezia?

This is very important for countries where regular wireguard is blocked.

In fact, there are just a few extra fields, it is no different from a regular wireguard. I think it's not that hard to add awg support.

https://github.com/amnezia-vpn/amneziawg-linux-kernel-module

**Comment by donaldzou** [comment]
Hi @RNDpacman, I think is doable but currently I'm focused on implementing features and fixing bugs for the next minor release. So I'll check it out later. :)

**Comment by potap1978** [comment]
> Планируется ли поддержка запутанной версии Wireguard от Amnezia?
> 
> Это очень важно для стран, где обычная беспроводная связь заблокирована.
> 
> На самом деле, там всего несколько дополнительных полей, ничем не отличается от обычного wireguard. Я думаю, что не так уж и сложно добавить поддержку awg.
> 
> https://github.com/amnezia-vpn/amneziawg-linux-kernel-module

This is the best idea. 👍👍👍👍👍👍👍

**Comment by EgorChadov** [comment]
Hey @donaldzou! It will be awesome if WGDashboard works with amneziawg. We have discussed this topic [before](https://github.com/donaldzou/WGDashboard/issues/325), I even tried to make some fixes to make it work, but my knowledge was not enough

**Comment by NOXCIS** [comment]
@EgorChadov @RNDpacman @potap1978 

https://github.com/NOXCIS/Wiregate/tree/amneziawg

- Full **AmneziaWG** support with backwards compatibility Done, over on the paranoid deployment of WGdashboard, Wiregate. 

- Modify **dev-docker-compose.yml** to your enviorment and then run 
- `docker compose -f dev-docker-compose.yml up`

> NOTE: Russian IOS users are unable to get the AmneziaWG app without sideloading. Due to Goverment restrictions.

Hopefully donny will improve support with frontend configs on the upsteam WGDashboard.

### Proof Of Concept 
Tested on Iphone with OSX docker server.

WireGuard Wireshark Packet Inspection Results
![WireGuard Wireshark Results](https://i.imgur.com/D9VyKeL.png)

AmneziaWG Packet Inspection Results
![enter image description here](https://i.imgur.com/2N0Zjfe.png)

**Comment by RNDpacman** [comment]
I don't understand what wiregate has to do with it, it's some kind of monstrous assembly of a dozen unnecessary containers. Will your panel support AmneziaWG?

**Comment by NOXCIS** [comment]
@RNDpacman Ignore the other containers, they are just used for  Anonymous DNS routing & Filtering in Wiregate

I dont plan on making a PR, so im leaving it up to Donald to add the peer creation and interface control functions to support AmneziaWG in WG-Dashboard. Everything needed is done except frontend config editing.

 Run this docker compose if you just want WG-Dashboard standalone that supports AmneziaWG out of the box.

```yaml

services:

  wg-dashboard:
    image: noxcis/wg-dashboard:terra-fuego-beta
    container_name: wg-dashboard
    hostname: wg-dashboard
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - wgd_configs:/etc/wireguard 
      - wgd_db:/opt/wireguarddashboard/src/db 
      - wgd_db:/opt/wireguarddashboard/src/dashboard_config

    environment:
    #Use Ofuscated Wireguard (AmneziaWG)
      - AMNEZIA_WG=true
    #Set Timezone
      - TZ=America/Chicago

    #Tor Settings 
    ##########################################################
      - WGD_TOR_PROXY=false
      - WGD_TOR_EXIT_NODES={ch}
      - WGD_TOR_DNS_EXIT_NODES={gb}
      - WGD_TOR_PLUGIN=snowflake #OPTIONS webtunnel, obfs4, snowflake
      - WGD_TOR_BRIDGES=false

    #WGDashboard Global Settings
    ##########################################################
      - WGD_WELCOME_SESSION=false
      - WGD_AUTH_REQ=false
      - WGD_USER=admin
      - WGD_PASS=admin
      - WGD_REMOTE_ENDPOINT=0.0.0.0
      - WGD_REMOTE_ENDPOINT_PORT=80
      - WGD_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0
      - WGD_KEEP_ALIVE=21
      - WGD_MTU=1420
      - WGD_PORT_RANGE_STARTPORT=4430

    #DNS Setiings Must Match
    ##########################################################
      - WGD_DNS="1.1.1.1, 1.0.0.1"
      - WGD_IPTABLES_DNS=1.1.1.1

      
    #Obfuscated Wireguard via AmneziaWG Junk Headder Settings
    #All parameters should be the same between Client and Server, except Jc - it can vary.
    #########################################################
      - WGD_JC=5 #Jc — 1 ≤ Jc ≤ 128; recommended range is from 3 to 10 inclusive
      - WGD_JMIN=500 #Jmin — Jmin < Jmax; recommended value is 50
      - WGD_JMAX=550 #Jmax — Jmin < Jmax ≤ 1280; recommended value is 1000
      - WGD_S1=30 #S1 — S1 < 1280; S1 + 56 ≠ S2; recommended range is from 15 to 150 inclusive
      - WGD_S2=40 #S2 — S2 < 1280; recommended range is from 15 to 150 inclusive
      - WGD_H1=123456 #H1/H2/H3/H4 — must be unique among each other; recommended range is from 5 to 2147483647 inclusive
      - WGD_H2=67543 #H2
      - WGD_H3=32345 #H3
      - WGD_H4=123123 #H4
    ports:
      - "4430-4433:4430-4433/udp" #UDP Interface Listen Ports
      - 8000:80/tcp #Comment Out for full network lockdown
      #Access the dashboard @ localhost:8000
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
    wgd_configs:
    wgd_db:
    
````
