### ISSUE TITLE
Enable/disable peers

### ISSUE THREAD

**Issue by Nikita01471** [donaldzou/WGDashboard#377]
Hello!
Have some issues whis enabled peers.

After testing buttons and use "disable peer", can't enable peers back. 
Deleting disabled peers is also unavailable.

**Comment by donaldzou** [comment]
Hi! Do you mind posting a screenshot please?

**Comment by Nikita01471** [comment]
![IMG_20240909_192821_499](https://github.com/user-attachments/assets/20671827-fda4-48af-8cd5-1cdfd8b2b2aa)

**Comment by NOXCIS** [comment]
@donaldzou its a bug in you 4.1 dev branch. Disabling peers with preshared keys breaks the config.

**Comment by DaanSelen** [comment]
> @donaldzou its a bug in you 4.1 dev branch. Disabling peers with preshared keys breaks the config.

v4.1 just got launched, is this still a bug? I was not able to reproduce with a preshared key.

**Comment by NOXCIS** [comment]
@DaanSelen Was fixed, now broken agiain among other things.

Running Demo below.

http://demo.noxcis.com:10086/
username: admin
password: catinthehat

**Comment by donaldzou** [comment]
Could not reproduce with Preshared Key enabled for a peer. Will close this issue for now as it is related to a previous version.

**Comment by NOXCIS** [comment]
def addpeer is missing the weird step to copy from file, probably forgot it in refractor.

demo.noxcis.com <-Running with your Digital Ocean Affialte Link
username: admin
password: 6j2KPfPTBUrTEKD

<img width="1306" alt="Screenshot 2024-11-14 at 4 56 58 AM" src="https://github.com/user-attachments/assets/d5081740-f000-4db5-870d-1f46330a07e7">
<img width="1553" alt="Screenshot 2024-11-14 at 4 52 36 AM" src="https://github.com/user-attachments/assets/ea7d7627-7bc4-49de-a39c-0f207241679b">
<img width="1379" alt="Screenshot 2024-11-14 at 4 59 47 AM" src="https://github.com/user-attachments/assets/1e5606b7-3d13-4a17-ae0d-9c556cda1f25">



Docker Compose Used
```yaml
services:
  wireguard-dashboard:
    image: donaldzou/wgdashboard:latest
    restart: unless-stopped
    container_name: wgdashboard
    #environment:
      #- tz=                # <--- Set container timezone, default: Europe/Amsterdam.
      #- global_dns=        # <--- Set global DNS address, default: 1.1.1.1.
      #- isolate=           # <--- Set the interfaces that will disallow peer communication, default: 'none'.
      #- public_ip=         # <--- Set public IP to ensure the correct one is chosen, defaulting to the IP give by ifconfig.me.
    ports:
      - 80:10086/tcp
      - 51820:51820/udp
    volumes:
      - conf:/etc/wireguard
      - data:/data
    cap_add:
      - NET_ADMIN

volumes:
  conf:
  data:

```
