### ISSUE TITLE
Untitled Peer

### ISSUE THREAD

**Issue by hadi-dindar** [donaldzou/WGDashboard#597]
how we can use other wiregurd panel wg0 interface backup in this panel ?
when i add my peers detail in /etc/wiregurd/wg0  it show me Untitled Peer in pannel .
how i can set a name in wg0.conf file for peers ?
and also for getting config detail in panel " 
Download & QR Code is not available due to no private key set for this peer" and i must be add private key of per peers by hand for getting QR.
is any way for solve this problem ?
Tnx

**Comment by DaanSelen** [comment]
Can you while masking or removing the private keys show the outputs of `wgdashboard.db`

```
sqlite> select * from wg0;
9sL64B1PBZE1hFv6YdgWUWJwV88t08oEyezdk2Ug+WQ=|CMsxPmBADg3N0/5QJ5tWpPA3jVSB3p3oWUpi3vVe/UM=|9.9.9.9|0.0.0.0/0|Test|0.0|0.0|0.0|(none)|stopped|No Handshake|10.0.0.2/32|0.0|0.0|0.0|1420|21|<Public_IP>|
```

You can see in my example I made a config with one peer, this one is called test.

If this does not answer your question please correct me.

**Comment by hadi-dindar** [comment]
> Can you while masking or removing the private keys show the outputs of `wgdashboard.db`
> 
> ```
> sqlite> select * from wg0;
> 9sL64B1PBZE1hFv6YdgWUWJwV88t08oEyezdk2Ug+WQ=|CMsxPmBADg3N0/5QJ5tWpPA3jVSB3p3oWUpi3vVe/UM=|9.9.9.9|0.0.0.0/0|Test|0.0|0.0|0.0|(none)|stopped|No Handshake|10.0.0.2/32|0.0|0.0|0.0|1420|21|<Public_IP>|
> ```
> 
> You can see in my example I made a config with one peer, this one is called test.
> 
> If this does not answer your question please correct me.

can you explaihn more about this code  please ?

**Comment by DaanSelen** [comment]
> > Can you while masking or removing the private keys show the outputs of `wgdashboard.db`
> > ```
> > sqlite> select * from wg0;
> > 9sL64B1PBZE1hFv6YdgWUWJwV88t08oEyezdk2Ug+WQ=|CMsxPmBADg3N0/5QJ5tWpPA3jVSB3p3oWUpi3vVe/UM=|9.9.9.9|0.0.0.0/0|Test|0.0|0.0|0.0|(none)|stopped|No Handshake|10.0.0.2/32|0.0|0.0|0.0|1420|21|<Public_IP>|
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can see in my example I made a config with one peer, this one is called test.
> > If this does not answer your question please correct me.
> 
> can you explaihn more about this code please ?

The example I showed is the Database entry which WGDashboard uses:

First the 2 keys separated by a `|` Then the DNS, then the allowed IP's, then the name called "Test".

If you wanted to update the name you can do the following:
```
UPDATE wg0 SET name = 'New_name' WHERE name = 'Test';
```
This will change the name from 'Test' to 'New_name'.

What you are probably going to need to do is insert these peers into the database. But before that, please wait for @donaldzou 's response on what routes you can take.

**Comment by donaldzou** [comment]
Closing due to inactivity

**Comment by nv6** [comment]
Why is this closed? The solution doesn't answer the question at all. @donaldzou claimed in #293 that setting peer names from an existing .conf (#258) is now possible, but never bothered to explain HOW.

**Comment by donaldzou** [comment]
@nv6 Hi, apologize for the confusion and I should've write it in the documentation. To have predefined names, you'll need to follow this format after each `[Peer]`:

```
[Peer]
#Name# = Peer 1
PublicKey = ....
```

**Comment by nv6** [comment]
I've already tried this, doesn't work.

**Comment by donaldzou** [comment]
It will need to be done during the first time when WGDashboard discover you peer

On Mar 3, 2026, at 3:06 PM, nivesh ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/73319848?s=20&v=4]nv6 left a comment (WGDashboard/WGDashboard#597)<https://github.com/WGDashboard/WGDashboard/issues/597#issuecomment-3989122346>

I've already tried this, doesn't work.

**Comment by nv6** [comment]
> the first time when WGDashboard discover you peer

From what file exactly? I'm already setting it inside wg0.conf, which gets loaded by my compose file at runtime (because the UI shows the correct peer configs but every single one is named "Untitled Peer"). I'm not sure where else it's supposed to be defined.

compose.yml:
```yml
services:
  wgdashboard:
    image: ghcr.io/wgdashboard/wgdashboard:v4.3.1
    cap_add:
      - NET_ADMIN
    environment:
      enable_totp: "false"
      username: *****
      password: *****
    ports:
      - 10086:10086/tcp
      - 51820:51820/udp
    restart: unless-stopped
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf
      - aconf:/etc/amnezia/amneziawg
      - data:/data
volumes:
  aconf:
  data:
```

wg0.conf:
```
[Interface]
ListenPort = 51820
Address = 10.8.0.1/24
PrivateKey = *****
SaveConfig = true
DNS = 9.9.9.9

[Peer]
#Name# = node1
PublicKey = *****
PresharedKey = *****
AllowedIPs = 10.8.0.2/32, 10.0.2.0/24

[Peer]
#Name# = node2
PublicKey = *****
PresharedKey = *****
AllowedIPs = 10.8.0.3/32, 10.0.3.0/24

...
```

**Comment by nv6** [comment]
Nevermind I figured it out, I had to copy the conf from a secondary location before entrypoint because it doesn't like the conf being mounted directly for some reason.

Regardless, it took way too long to deduce the `#Name#` syntax in the first place from some obscure regex pattern. It really should be added to the documentation.

---

updated compose, in case this helps anyone in the future:
```yml
services:
  wgdashboard:
    image: ghcr.io/wgdashboard/wgdashboard:v4.3.1
    cap_add:
      - NET_ADMIN
    environment:
      enable_totp: "false"
      username: *****
      password: *****
    ports:
      - 10086:10086/tcp
      - 51820:51820/udp
    restart: unless-stopped
    volumes:
      - ./wg0.conf:/mnt/wg0.conf
      - aconf:/etc/amnezia/amneziawg
      - conf:/etc/wireguard
      - data:/data
    entrypoint: >
      /bin/bash -c "
      cp /mnt/wg0.conf /etc/wireguard/wg0.conf &&
      /bin/bash /entrypoint.sh
      "
volumes:
  aconf:
  conf:
  data:
```
