### ISSUE TITLE
Error when enabling wg0 using default config // iptables: Failed to initialize nft: Protocol not supported

### ISSUE THREAD

**Issue by SX86** [donaldzou/WGDashboard#716]
**Describe The Problem**
Unable to bring up wg0 using default PreUp/PostUp configuration. It seems the version of iptables that is bundled with the docker image is not compatible with my environment, not certain.
I was using [wg-easy](https://github.com/wg-easy/wg-easy) previously and did not encounter this error.

**Expected Error / Traceback**
```
iptables: Failed to initialize nft: Protocol not supported
```

**To Reproduce**
To run the dashboard, I use the docker compose method using the following docker-compose.yml
```
services:
  wireguard-dashboard:
    image: donaldzou/wgdashboard:latest
    restart: unless-stopped
    container_name: wgdashboard
    hostname: wgdashboard
    network_mode: bridge
    environment:
      - tz=America/Toronto
      - wgd_port=10086
      - global_dns=192.168.1.3
    ports:
      - 10086:10086/tcp
      - 51820:51820/udp
    volumes:
      - ./wireguard:/etc/wireguard
      - ./data:/data
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

**Steps to fix:**
I added the following commands to the `PreUp` portion of my wg0.conf file.
```
apk add dpkg iptables-legacy
update-alternatives --install /usr/sbin/iptables iptables /usr/sbin/iptables-legacy 20
update-alternatives --install /usr/sbin/ip6tables ip6tables /usr/sbin/ip6tables-legacy 20
```
No issues with enabling wg0 after running these commands.

**OS Information:**
 - OS: Synology DSM 6.2.4-25556 Update 8
 - Synology Kernel modules from https://github.com/runfalk/synology-wireguard
 - Python Version: Python 3.12.10

**Sample of your `.conf` file**
```
[Interface]
ListenPort = 51820
DNS = 192.168.1.3
PostDown = iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT;
PreDown = 
PostUp = iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
PreUp = apk add dpkg iptables-legacy; update-alternatives --install /usr/sbin/iptables iptables /usr/sbin/iptables-legacy 20; update-alternatives --install /usr/sbin/ip6tables ip6tables /usr/sbin/ip6tables-legacy 20
Address = 10.8.0.1/24
PrivateKey = xxxxABCDxxxx=
```
