### ISSUE TITLE
WGDashboard docker version not showing CPU/MEM stats

### ISSUE THREAD

**Issue by jcastro** [donaldzou/WGDashboard#798]
**Describe The Problem**
Docker version seems to not show the CPU/Memory widgets at the top of the dashbord

**Expected Error / Traceback**
```
Please provide the error traceback here
```

**To Reproduce**
I just used the regular docker compose file from Dan and that seems to be enough to reproduce it. I did also tried WGD using Helper scripts on Proxmox and the stats do show up at the top of the page!

**OS Information:**
 - Debian 12
 - Running docker version (latests ones as per the official docker repo)
 -

**Docker compose file**
```
services:
  wireguard-dashboard:
    image: donaldzou/wgdashboard:latest
    restart: unless-stopped
    container_name: wgdashboard
    #environment:
      #- tz=                # <--- Set container timezone, default: Europe/Amsterdam.
      #- public_ip=         # <--- Set public IP to ensure the correct one is chosen, defaulting to the IP give by ifconfig.me.
      #- wgd_port=          # <--- Set the port WGDashboard will use for its web-server.
    ports:
      - 10086:10086/tcp
      - 51820:51820/udp
      - 52820:52820/udp
      - 52821:52821/udp
    volumes:
      - aconf:/etc/amnezia/amneziawg
      - conf:/etc/wireguard
      - data:/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
      - net.ipv4.conf.all.src_valid_mark=1
volumes:
  aconf:
  conf:
  data:
```
**Useful files**

<img width="1266" alt="Image" src="https://github.com/user-attachments/assets/c5bba38f-4ae9-4a37-b90d-9a8f67830979" />
https://github.com/user-attachments/assets/0c3083f9-8d2a-4a32-ae26-8fc665e165da
